sudo: required
services:
  - docker

before_install:
  - docker build -t clbxrn/docker-udemy-course -f Dockerfile.dev .
script:
  - docker run -e CI=true clbxrn/docker-udemy-course npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-udemy-course"
  env: "DockerUdemyCourse-env"
  bucket_name: "elasticbeanstalk-eu-central-1-510210436455"
  bucket_path: "docker-udemy-course"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY