sudo: required
services:
  - docker

before_install:
  - docker build -t clbxrn/docker-udemy-course -f Dockerfile.dev .
script:
  - docker run -e CI=true clbxrn/docker-udemy-course npm run test -- --coverage