version: '3'
services:
  react-app-web:
    build:
      # which are the files and folders which should be included into the container
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      # map the current folder outside the container
      # into the app folder inside the container
      - ./:/app
  test-the-same-app:
      build:
        context: ./
        dockerfile: Dockerfile.dev
      volumes:
        - /app/node_modules
        - .:/app
      # overwrite the default command
      command: ['npm', 'run', 'test']